// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFl25k-ZkWa0k5gAwSJSSv_4lH03UwUb8',
    appId: '1:396132068167:web:3f6000e47a87266949ba62',
    messagingSenderId: '396132068167',
    projectId: 'hotelreservation-5bdc9',
    authDomain: 'hotelreservation-5bdc9.firebaseapp.com',
    storageBucket: 'hotelreservation-5bdc9.appspot.com',
    measurementId: 'G-1WHLC2CXBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUG-v0Ukh2BBVWu8nyKxru3WDwet7XAKc',
    appId: '1:396132068167:android:027e36cde1cc5e8f49ba62',
    messagingSenderId: '396132068167',
    projectId: 'hotelreservation-5bdc9',
    storageBucket: 'hotelreservation-5bdc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DhDtNgxJN0suCDyBl18lN568hARD30M',
    appId: '1:396132068167:ios:64b378047691cd1f49ba62',
    messagingSenderId: '396132068167',
    projectId: 'hotelreservation-5bdc9',
    storageBucket: 'hotelreservation-5bdc9.appspot.com',
    iosBundleId: 'com.example.hotelReservationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DhDtNgxJN0suCDyBl18lN568hARD30M',
    appId: '1:396132068167:ios:64b378047691cd1f49ba62',
    messagingSenderId: '396132068167',
    projectId: 'hotelreservation-5bdc9',
    storageBucket: 'hotelreservation-5bdc9.appspot.com',
    iosBundleId: 'com.example.hotelReservationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFl25k-ZkWa0k5gAwSJSSv_4lH03UwUb8',
    appId: '1:396132068167:web:2fb9aa1537c6bf3349ba62',
    messagingSenderId: '396132068167',
    projectId: 'hotelreservation-5bdc9',
    authDomain: 'hotelreservation-5bdc9.firebaseapp.com',
    storageBucket: 'hotelreservation-5bdc9.appspot.com',
    measurementId: 'G-K6WVH2QJ26',
  );
}
